#!/bin/bash
#
#SBATCH --chdir=/path/Apocynaceae_allraw_2024
#SBATCH --job-name=fastqc
#SBATCH --partition=long
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=4G
#SBATCH --export=ALL
#SBATCH --mail-user=email@kew.org
#SBATCH --mail-type=END,FAIL

# Run FastQC on all FASTQ files in the current directory.
for f in *.fastq.gz; 
do (fastqc $f); 
done
# Loops through all files ending with `.fastq.gz` in the working directory.
# Executes FastQC on each file to generate quality reports (.zip and .html files).

# Create a directory to store the FastQC output.
mkdir /path/Apocynaceae_allraw_2024/fastqc_pre_trim_all
# Creates a subdirectory named "fastqc_pre_trim_all" to organise FastQC reports.

# Move FastQC output files to the newly created directory.
mv *.zip /path/Apocynaceae_allraw_2024/fastqc_pre_trim_all
mv *.html /path/Apocynaceae_allraw_2024/fastqc_pre_trim_all
# Moves the .zip and .html files generated by FastQC to the "fastqc_pre_trim_all" directory.

# Use MultiQC to aggregate and summarise FastQC reports.
# https://protect-eu.mimecast.com/s/KNJjCJNR8HBXL6VuGJ4GB/
multiqc ./
# Aggregates all FastQC output files in the current directory into a single MultiQC report.
# This provides a comprehensive summary of quality metrics for all sequencing files.
